# Generated by Django 5.1.3 on 2025-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('csv_path', models.TextField(null=True)),
            ],
        ),
    ]
