# Generated by Django 5.1.3 on 2025-03-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalanomaly', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video_url',
        ),
    ]
